//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanLearning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class michiyf248_clEntities : DbContext
    {
        public michiyf248_clEntities()
            : base("name=michiyf248_clEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<ModuleSubscription> ModuleSubscription { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<QuestionFeedback> QuestionFeedback { get; set; }
        public virtual DbSet<QuestionResult> QuestionResult { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TestResult> TestResult { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<TeacherSkill> TeacherSkill { get; set; }
        public virtual DbSet<QuestionResultFeedback> QuestionResultFeedback { get; set; }
        public virtual DbSet<TestResultFeedback> TestResultFeedback { get; set; }
        public virtual DbSet<AnswerOption> AnswerOption { get; set; }
        public virtual DbSet<FAQ> FAQ { get; set; }
        public virtual DbSet<TestFeedback> TestFeedback { get; set; }
        public virtual DbSet<SupportingTeacher> SupportingTeacher { get; set; }
        public virtual DbSet<ModuleRequirements> ModuleRequirements { get; set; }
        public virtual DbSet<NewFAQ> NewFAQ { get; set; }
    }
}
